# Generated by Django 3.0.8 on 2020-07-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200710_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dtEdited',
            new_name='dTEdited',
        ),
    ]
