# Generated by Django 3.0.8 on 2020-07-13 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='current_user',
        ),
        migrations.AlterField(
            model_name='follower',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
