# Generated by Django 3.0.8 on 2020-07-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200713_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='users',
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
