# Generated by Django 3.0.8 on 2020-07-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200713_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='first',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
