# Generated by Django 3.0.8 on 2020-07-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_follower_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='first',
        ),
    ]
