# Generated by Django 3.0.8 on 2020-07-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Edited',
            field=models.BooleanField(default=False),
        ),
    ]
