# Generated by Django 3.0.8 on 2020-07-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20200724_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
