# Generated by Django 3.0.8 on 2020-07-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20200724_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dTEdited',
            field=models.DateTimeField(verbose_name='date_edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dTEdited',
            field=models.DateTimeField(verbose_name='date_edited'),
        ),
    ]
