# Generated by Django 3.0.8 on 2020-07-25 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20200725_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dTEdited',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dTEdited',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date_edited'),
        ),
    ]
